// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkWabEBvBqKHoL7xTvRt9YaAAl8ejZxNk',
    appId: '1:451908682839:web:86eabf986a4158911c4f12',
    messagingSenderId: '451908682839',
    projectId: 'flash-chatt-e10e8',
    authDomain: 'flash-chatt-e10e8.firebaseapp.com',
    storageBucket: 'flash-chatt-e10e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMTKOx32_ASwpQFjbeL9duh-CPHsMax48',
    appId: '1:451908682839:android:54e4b3cace5b49631c4f12',
    messagingSenderId: '451908682839',
    projectId: 'flash-chatt-e10e8',
    storageBucket: 'flash-chatt-e10e8.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaF8eh-FVtOPdCvC1kL07AwPd1K5d5aGU',
    appId: '1:451908682839:ios:23f7e224ce09f1c41c4f12',
    messagingSenderId: '451908682839',
    projectId: 'flash-chatt-e10e8',
    storageBucket: 'flash-chatt-e10e8.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );
}
